### PR TITLE
Feature/game view improvements clean

### PR DESCRIPTION
**Pull request by Rojo**
* Display `document` and `whiteboard` data alongside with columns. (Whiteboard is currently an example).
* Calculate the height of the columns as a percentage of pixels with respect to the window height and activate scrollbars if the content overflows. (Currently set to 50% of the window height).
* Update specs.
* Cleaner commit history.

Related to https://github.com/Xiaohong-Deng/mooqita-icccg/issues/44
Supersedes https://github.com/Xiaohong-Deng/mooqita-icccg/pull/53

image

### CODE REVIEW

**Comment by Rojo** [comment]
@Xiaohong-Deng I have not found any working conflict with Jacob's code.

**Comment by Rojo** [comment]
@Xiaohong-Deng Seems that the merging of https://github.com/Xiaohong-Deng/mooqita-icccg/pull/54 introduced a regression, suppressing a couple of commits. Will try to cherry-pick the commits again.

**Comment by Xiaohong-Deng** [comment]
@Rojo Thanks. please do that. As for the `turbolinks` conflicts, Jacob did mention it and said he removed it because of that. If we add it back and unexpected behavior happens later, how we're gonna tell if it's the conflicts in `turbolinks` and Jacob's code or it's just bugs introduced by my coding? yes we can remove `turbolinks` first to see if it's the former. anyway I want to avoid this if possible.

**Comment by Xiaohong-Deng** [comment]
@Rojo is `turbolinks` for scrolling down on page loading? if that's the case, leave this feature for me. let me handle it.

**Comment by Rojo** [comment]
@Xiaohong-Deng Yes. For some reason the `$(document).ready` event did not work for me while testing the scripts but I'll check too if something can be done about it.

**Comment by Xiaohong-Deng** [comment]
@Rojo If Jacob made regression tests on this, it would be easier for us to add `turbolinks`. but I'm sure he didn't.

**Comment by Xiaohong-Deng** [comment]
@Rojo I was coding `ACtionCable` for green today. `$(document).ready` works for me. I noticed there are residuals of `turbolinks`. Try the following. Or you can leave it to me. I already have done it.

1. Remove the gem 'turbolinks' line from your Gemfile, and then run bundle
update to update your Gemfile.lock, so it’s truly gone.
2. Remove the //= require turbolinks line from app/assets/javascripts/
application.js.
3. Change the stylesheet and JavaScript loading lines near the top of app/views/
layouts/application.html.erb. Afterward, they should look like this:
```
<%= stylesheet_link_tag 'application', media: 'all' %>

<%= javascript_include_tag 'application' %>
```

**Comment by Rojo** [comment]
@Xiaohong-Deng That worked!

Now just have to check why my local `master` is ahead of remote `master`...

**Comment by Rojo** [comment]
@Xiaohong-Deng Ready on PR https://github.com/Xiaohong-Deng/mooqita-icccg/pull/57.

**Pull request closed without merging**
